### ISSUE TITLE
h2-console 이슈 기록

### ISSUE THREAD

**Issue by zhyunk** [zhyun-project/simple-board-02#76]
H2 Console
Sorry, remote connections ('webAllowOthers') are disabled on this server.

![Image](https://github.com/zhyun-project/simple-board-02/assets/31812307/cab9453d-7fef-4051-a8ad-e50f944bf694)

해결 : https://corsprscsl.tistory.com/51

applicatoin.yml에 다음 설정을 추가
```yml
spring:
  h2:
    console:
      settings:
        web-allow-others: true

```

#### ✏️ web-allow-othsers 옵션
다른 네트워크 사용자의 접근 허용 여부를 설정하는 옵션이다.
이 옵션을 true 로 설정하면 localhost(127.0.0.1)이 아닌 네트워크 사용자의 접속을 허용하는 셈이 된다.
기본 설정 값은 false이다.
