### ISSUE TITLE
workflow 리팩토링 시도 - build job의 docker 코드 deploy job으로 옮기기 

### ISSUE THREAD

**Issue by zhyunk** [zhyun-project/simple-board-02#96]
https://github.com/zhyun-project/simple-board-02/blob/0081947c83bfabdbbbc698da6396a8e38f31c977/.github/workflows/deploy.yml#L41-L50
- artifacts 사용해서 deploy job으로 이동해보기 
  ```yml
  - name: Upload build artifacts
    uses: actions/upload-artifact@v3
    with:
      name: build-artifacts
      path: |
        discovery/build/libs/
        simpleBoard02/build/libs/

   - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
  ```
