### ISSUE TITLE
github action workflows 리팩토링 시도 - artifact 적용해 보기

### ISSUE THREAD

**Issue by zhyunk** [zhyun-project/simple-board-02#97]
## artifact 적용 
- [x] build job의 docker 코드 deploy job으로 옮기기
https://github.com/zhyun-project/simple-board-02/blob/0081947c83bfabdbbbc698da6396a8e38f31c977/.github/workflows/deploy.yml#L41-L50
   - artifact  ex  
     ```yml
     - name: Upload build artifacts
       uses: actions/upload-artifact@v3
       with:
         name: build-artifacts
         path: |
           discovery/build/libs/
           simpleBoard02/build/libs/

     - name: Download build artifacts
       uses: actions/download-artifact@v3
       with:
         name: build-artifacts
     ```

<br>

- [x] artifact 사용해서 일부 job의 actions/checkout 코드 삭제 시도
